import type { Id } from '@domain/types.ts'
import type { AppContext } from '../context.ts'
import { createOperationsService } from '../services/operations.service.ts'
import { createRng } from './rng.ts'
import {
  CATEGORIES,
  CUSTOMERS,
  INTERNAL_LOCATIONS,
  PRODUCTS,
  WAREHOUSES,
  type SeedProduct,
  type WarehouseCode,
} from './seed-data.ts'

const DAY_MS = 86_400_000
const HISTORY_DAYS = 90
const LOW_STOPS_REORDERING = -18
const OUT_STOPS_REORDERING = -25
const CYCLE_COUNT_DAYS = new Set([-62, -33, -9])

/**
 * Deterministic 90-day history, generated by driving the *real* operations service with a
 * simulated clock — so every seeded document obeyed the same lifecycle and availability
 * rules the app enforces, and the ledger reconciles by construction.
 */
export function seedDemo(ctx: AppContext, opts: { now?: Date } = {}) {
  const realNow = opts.now ?? ctx.now()
  const rng = createRng(20260926)
  let simNow = realNow
  const ops = createOperationsService({ ...ctx, now: () => simNow })
  const { catalog, stock } = ctx

  const today = Date.UTC(realNow.getUTCFullYear(), realNow.getUTCMonth(), realNow.getUTCDate())
  let minute = 0
  /** Advance the simulated clock within day `d` (09:00 IST onward, one minute per event). */
  const tick = (d: number) => {
    simNow = new Date(today + d * DAY_MS + (210 + minute++) * 60_000)
    return simNow.toISOString()
  }
  const dateOf = (d: number) => new Date(today + d * DAY_MS + 210 * 60_000).toISOString()

  ctx.db.tx(() => {
    // ── Master data ────────────────────────────────────────────────────────────
    const categoryId = new Map(CATEGORIES.map((c) => [c, catalog.insertCategory(c)]))
    catalog.insertLocation({ warehouseId: null, name: 'Vendors', kind: 'vendor' })
    catalog.insertLocation({ warehouseId: null, name: 'Customers', kind: 'customer' })
    catalog.insertLocation({ warehouseId: null, name: 'Inventory adjustment', kind: 'adjustment' })

    const loc = new Map<WarehouseCode, Record<(typeof INTERNAL_LOCATIONS)[number], Id>>()
    for (const w of WAREHOUSES) {
      const warehouseId = catalog.insertWarehouse(w)
      const ids = {} as Record<(typeof INTERNAL_LOCATIONS)[number], Id>
      for (const name of INTERNAL_LOCATIONS) ids[name] = catalog.insertLocation({ warehouseId, name, kind: 'internal' })
      loc.set(w.code, ids)
    }

    const productId = new Map<string, Id>()
    const created = new Date(today - (HISTORY_DAYS + 1) * DAY_MS).toISOString()
    for (const p of PRODUCTS) {
      productId.set(
        p.sku,
        catalog.insertProduct(
          {
            sku: p.sku,
            name: p.name,
            categoryId: categoryId.get(p.category)!,
            uom: p.uom,
            cost: p.cost,
            price: p.price,
            reorderMin: p.min,
            reorderMax: p.max,
            leadTimeDays: p.lead,
            supplier: p.supplier,
          },
          created,
        ),
      )
    }
    const pid = (p: SeedProduct) => productId.get(p.sku)!
    const stockLoc = (w: WarehouseCode) => loc.get(w)!.Stock
    const perWh = (p: SeedProduct, n: number) => Math.ceil(n / p.homes.length)

    // ── Opening balances (day −90) ────────────────────────────────────────────
    for (const p of PRODUCTS) {
      for (const w of p.homes) {
        tick(-HISTORY_DAYS)
        const qty = p.profile === 'dead' ? Math.ceil(perWh(p, p.min) * 1.5) : perWh(p, p.max)
        ops.postInitialStock(pid(p), stockLoc(w), qty)
      }
    }

    // ── Daily simulation ─────────────────────────────────────────────────────
    type Pending = { opId: Id; arrivalDay: number; wh: WarehouseCode; lines: { productId: Id; qty: number }[] }
    const pending: Pending[] = []
    const incoming = new Map<string, number>()
    const key = (productIdValue: Id, w: WarehouseCode) => `${productIdValue}@${w}`

    const sampleDemand = (d: number) => {
      if (d <= 0) return 0
      if (d < 1) return rng.chance(d) ? 1 : 0
      return Math.max(0, Math.round(d * (0.3 + 1.4 * rng.next())))
    }

    for (let d = -HISTORY_DAYS + 1; d <= -1; d++) {
      minute = 0

      // 1. Morning: receipts due today arrive and are validated.
      for (const r of pending.filter((x) => x.arrivalDay === d)) {
        tick(d)
        ops.validate(r.opId)
        for (const l of r.lines) incoming.set(key(l.productId, r.wh), (incoming.get(key(l.productId, r.wh)) ?? 0) - l.qty)
      }

      for (const w of WAREHOUSES.map((x) => x.code)) {
        // 2. Customer orders: pick → pack → validate, clipped to what the shelf holds.
        const lines: { productId: Id; qty: number }[] = []
        for (const p of PRODUCTS.filter((x) => x.homes.includes(w) && x.profile !== 'dead')) {
          const want = sampleDemand(p.demand)
          const have = Math.floor(stock.qtyAt(pid(p), stockLoc(w)))
          const qty = Math.min(want, have)
          if (qty > 0) lines.push({ productId: pid(p), qty })
        }
        const orders = Math.min(lines.length, rng.int(1, 3))
        for (let o = 0; o < orders; o++) {
          const orderLines = lines.filter((_, i) => i % orders === o)
          tick(d)
          const op = ops.create({
            type: 'delivery',
            partner: rng.pick(CUSTOMERS),
            sourceLocationId: stockLoc(w),
            scheduledDate: dateOf(d),
            lines: orderLines,
          })
          ops.confirm(op.id)
          ops.pick(op.id)
          ops.pack(op.id)
          ops.validate(op.id)
        }

        // 3. Weekly internal moves for normal products: overflow to Rack A, raw materials to the floor.
        if ((d + HISTORY_DAYS) % 7 === 3) {
          for (const p of PRODUCTS.filter((x) => x.homes.includes(w) && x.profile === 'normal').slice(0, 2)) {
            const qty = Math.floor(stock.qtyAt(pid(p), stockLoc(w)) * 0.08)
            if (qty < 1) continue
            const dest = p.category === 'Raw Materials' ? loc.get(w)!['Production Floor'] : loc.get(w)!['Rack A']
            tick(d)
            const op = ops.create({ type: 'transfer', sourceLocationId: stockLoc(w), destLocationId: dest, scheduledDate: dateOf(d), lines: [{ productId: pid(p), qty }] })
            ops.validate(op.id)
          }
        }

        // 4. Cycle counts: small, realistic discrepancies.
        if (CYCLE_COUNT_DAYS.has(d)) {
          const candidates = PRODUCTS.filter((x) => x.homes.includes(w) && x.profile === 'normal')
          for (let i = 0; i < 3; i++) {
            const p = rng.pick(candidates)
            const system = stock.qtyAt(pid(p), stockLoc(w))
            const delta = p.uom === 'unit' || p.uom === 'box' ? rng.pick([-2, -1, -1, 1]) : -Math.max(1, Math.round(system * 0.01))
            tick(d)
            const op = ops.create({
              type: 'adjustment',
              destLocationId: stockLoc(w),
              reason: rng.pick(['Cycle count', 'Damaged', 'Cycle count']),
              scheduledDate: dateOf(d),
              lines: [{ productId: pid(p), qty: Math.max(0, system + delta) }],
            })
            ops.validate(op.id)
          }
        }

        // 5. Evening: the min/max rule raises receipts, grouped per supplier.
        const bySupplier = new Map<string, { lines: { productId: Id; qty: number }[]; lead: number }>()
        for (const p of PRODUCTS.filter((x) => x.homes.includes(w))) {
          if (p.profile === 'dead') continue
          if (p.profile === 'low' && d >= LOW_STOPS_REORDERING) continue
          if (p.profile === 'out' && d >= OUT_STOPS_REORDERING) continue
          const forecast = stock.qtyAt(pid(p), stockLoc(w)) + (incoming.get(key(pid(p), w)) ?? 0)
          // Reorder point = minimum + expected demand over the lead time, so stock arrives before it dips.
          if (forecast > perWh(p, p.min) + p.demand * p.lead) continue
          const qty = Math.ceil(perWh(p, p.max) - forecast)
          const entry = bySupplier.get(p.supplier) ?? { lines: [], lead: 0 }
          entry.lines.push({ productId: pid(p), qty })
          entry.lead = Math.max(entry.lead, p.lead)
          bySupplier.set(p.supplier, entry)
        }
        for (const [supplier, { lines: receiptLines, lead }] of bySupplier) {
          tick(d)
          const arrivalDay = d + lead
          const op = ops.create({
            type: 'receipt',
            partner: supplier,
            destLocationId: stockLoc(w),
            scheduledDate: dateOf(arrivalDay),
            lines: receiptLines,
          })
          ops.confirm(op.id)
          pending.push({ opId: op.id, arrivalDay, wh: w, lines: receiptLines })
          for (const l of receiptLines) incoming.set(key(l.productId, w), (incoming.get(key(l.productId, w)) ?? 0) + l.qty)
        }
      }
    }

    // ── End state for the story (yesterday evening) ─────────────────────────────
    minute = 600
    const onHand = stock.onHandByProduct()
    for (const p of PRODUCTS.filter((x) => x.profile === 'low' || x.profile === 'out')) {
      const target = p.profile === 'out' ? 0 : Math.round(p.min * 0.6)
      let excess = (onHand.get(pid(p)) ?? 0) - target
      if (excess < 0) {
        // Drained past the target: a partial shipment from the supplier tops it up.
        tick(-1)
        const op = ops.create({ type: 'receipt', partner: p.supplier, destLocationId: stockLoc(p.homes[0]), scheduledDate: dateOf(-1), lines: [{ productId: pid(p), qty: -excess }] })
        ops.validate(op.id)
        continue
      }
      for (const w of p.homes) {
        const have = Math.floor(stock.qtyAt(pid(p), stockLoc(w)))
        const qty = Math.min(have, Math.ceil(excess))
        if (qty <= 0) continue
        tick(-1)
        const op = ops.create({ type: 'delivery', partner: rng.pick(CUSTOMERS), sourceLocationId: stockLoc(w), scheduledDate: dateOf(-1), lines: [{ productId: pid(p), qty }] })
        ops.confirm(op.id)
        ops.pick(op.id)
        ops.pack(op.id)
        ops.validate(op.id)
        excess -= qty
      }
    }

    // ── Today: open work across every status ───────────────────────────────────
    let k = 0
    const recent = () => {
      simNow = new Date(realNow.getTime() - (90 - k++) * 60_000)
    }
    const bySku = (sku: string) => productId.get(sku)!

    recent()
    const waiting = ops.create({ type: 'delivery', partner: 'Apollo Hospitals', sourceLocationId: stockLoc('BOM'), scheduledDate: dateOf(-1), lines: [{ productId: bySku('EL-UPS-1K'), qty: 3 }] })
    ops.confirm(waiting.id)

    recent()
    const picking = ops.create({
      type: 'delivery',
      partner: 'L&T Construction',
      sourceLocationId: stockLoc('HYD'),
      scheduledDate: dateOf(0),
      lines: [
        { productId: bySku('RM-STL-012'), qty: 120 },
        { productId: bySku('SF-HELMET'), qty: 20 },
      ],
    })
    ops.confirm(picking.id)
    if (ops.get(picking.id).status === 'ready') ops.pick(picking.id, ops.get(picking.id).lines[0].id)

    recent()
    const overdue = ops.create({ type: 'delivery', partner: 'Flipkart Warehouse', sourceLocationId: stockLoc('BLR'), scheduledDate: dateOf(-2), lines: [{ productId: bySku('PK-BOX-M'), qty: 150 }] })
    ops.confirm(overdue.id)

    recent()
    ops.create({
      type: 'delivery',
      partner: 'Mahindra Logistics',
      sourceLocationId: stockLoc('BOM'),
      scheduledDate: dateOf(1),
      lines: [
        { productId: bySku('PK-BOX-L'), qty: 80 },
        { productId: bySku('SF-GLOVE-C'), qty: 5 },
      ],
    })

    recent()
    ops.create({ type: 'receipt', partner: 'Navneet Office', destLocationId: stockLoc('HYD'), scheduledDate: dateOf(2), lines: [{ productId: bySku('OF-A4-RM'), qty: 20 }] })

    recent()
    const late = ops.create({ type: 'receipt', partner: 'Uflex Packaging', destLocationId: stockLoc('BOM'), scheduledDate: dateOf(-1), lines: [{ productId: bySku('PK-TAPE-48'), qty: 30 }] })
    ops.confirm(late.id)

    recent()
    const rebalance = ops.create({ type: 'transfer', sourceLocationId: stockLoc('HYD'), destLocationId: stockLoc('BLR'), scheduledDate: dateOf(1), lines: [{ productId: bySku('EL-LED-36W'), qty: 20 }] })
    ops.confirm(rebalance.id)

    recent()
    ops.create({ type: 'transfer', sourceLocationId: loc.get('BLR')!['Rack A'], destLocationId: loc.get('BLR')!['Rack B'], scheduledDate: dateOf(0), lines: [{ productId: bySku('PK-BOX-M'), qty: 40 }] })
  })

  return { moves: stock.countMoves(), operations: ctx.operations.list().length }
}

